"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-template' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Peer package NOT installed (peer standalone absent in the CI env) →
  test is SKIPPED. The skip is taken on the ROOT distribution only
  (`scitex_io`), never on the full dotted path: skipping on the full
  path would swallow a renamed submodule as "not installed" and report
  green, which is the exact failure this gate exists to catch.
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex_config._ecosystem",
    "scitex_dev",
    "scitex_dev._cli._completion",
    "scitex_git",
    "scitex_scholar.ensure_workspace",
    "scitex_writer",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_succeeds_or_skips(module_name):
    """Importing scitex-template's declared cross-package dependency must succeed."""
    # Arrange
    # Skip on the ROOT package only, then hard-import the FULL dotted path,
    # so a renamed submodule raises instead of being skipped into a green.
    pytest.importorskip(module_name.split(".")[0])
    # Act
    module = importlib.import_module(module_name)
    # Assert
    assert module is not None
